---
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/mnt/lexicon/Mail/gmail/Inbox
  usual: true
  archived: false
  sync_back: true
  id: 1
  labels:
  - GMail
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/mnt/lexicon/Mail/ugent/Inbox
  usual: true
  archived: false
  sync_back: true
  id: 3
  labels:
  - UGent
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/mnt/lexicon/Mail/12ul/Inbox
  usual: true
  archived: false
  sync_back: true
  id: 5
  labels:
  - 12UL
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/mnt/lexicon/Mail/gmail/Sent
  usual: true
  archived: true
  sync_back: true
  id: 2
  labels:
  - GMail
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/mnt/lexicon/Mail/ugent/Sent
  usual: true
  archived: true
  sync_back: true
  id: 4
  labels:
  - UGent
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/mnt/lexicon/Mail/12ul/Sent
  usual: true
  archived: true
  sync_back: true
  id: 6
  labels:
  - 12UL
- !supmua.org,2006-10-01/Redwood/SentLoader {}
